### ISSUE TITLE
Expression of interest: Fed-BioMed

### ISSUE THREAD

**Issue by sharkovsky** [securefederatedai/federated-standards#1]
Hello, 

thank you for setting up this nice initiative! 
I would like to express an interest for the software [Fed-BioMed](https://github.com/fedbiomed/fedbiomed) to take part in the discussion. 
We target cross-silo FL in the healthcare and clinical domains, and we have demonstrated deployments as part of national (French) and international (EU) projects. 

Please let me know how we can continue this discussion.

**Comment by psfoley** [comment]
Thanks @sharkovsky for expressing Fed-BioMed's interest in contributing to [federated-standards](https://github.com/securefederatedai/federated-standards)! Sorry for the delay in getting back to this message - we have been at the ideation phase for potential standards over the last few months, but you'll start seeing more frequent updates here soon. We currently have a biweekly call between the OpenFL and Flower teams about standards and common components. If you're still interested, send me an email at patrick.foley@intel.com and we can coordinate next steps!

**Comment by sharkovsky** [comment]
Thank you very much @psfoley! I'll contact you via email.
